data:
  filepath: "./data/raw/ai4i2020.csv"
  processed: ./data/processed/
  models: ./models/

models:
  logistic_regression:
    max_iter: 1000
  random_forest:
    n_estimators: 100
    max_depth: 10

mlflow:
  experiment_name: "Predictive Maintenance Analysis V1"
  tracking_uri: "http://127.0.0.1:5000"